<a href="https://colab.research.google.com/github/Yury122/An-lisis-y-Dise-o-de-Algoritmos-2025-2-/blob/main/TAREA_PCA_MATRIZ_3X3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
#creo la matriz X
X = np.array([[2,0,1],
             [3,1,2],
             [4,0,3]
             ])

In [4]:
X

array([[2, 0, 1],
       [3, 1, 2],
       [4, 0, 3]])

In [6]:
mean = np.mean(X,axis=0)
mean

array([3.        , 0.33333333, 2.        ])

In [10]:
X_centered = X - mean
X_centered

array([[-1.        , -0.33333333, -1.        ],
       [ 0.        ,  0.66666667,  0.        ],
       [ 1.        , -0.33333333,  1.        ]])

In [11]:
cov_matrix = np.cov(X_centered, rowvar=False)
cov_matrix

array([[1.        , 0.        , 1.        ],
       [0.        , 0.33333333, 0.        ],
       [1.        , 0.        , 1.        ]])

In [18]:
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

In [20]:
eigenvalues

array([2.        , 0.        , 0.33333333])

In [19]:
eigenvectors

array([[ 0.70710678, -0.70710678,  0.        ],
       [ 0.        ,  0.        ,  1.        ],
       [ 0.70710678,  0.70710678,  0.        ]])

In [21]:
sorted_idx = np.argsort(eigenvalues)[::-1]
eigenvalues = eigenvalues[sorted_idx]
eigenvectors = eigenvectors[:, sorted_idx]


In [23]:
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [2.         0.33333333 0.        ]
Eigenvectors:
 [[ 0.70710678  0.         -0.70710678]
 [ 0.          1.          0.        ]
 [ 0.70710678  0.          0.70710678]]


In [24]:
k = 1
X_pca = X_centered.dot(eigenvectors[:, :k])

In [26]:
print("Original data shape:", X.shape)
print("Transformed data shape:", X_pca.shape)
print("Projected data (first 5 samples):\n", X_pca[:5])

Original data shape: (3, 3)
Transformed data shape: (3, 1)
Projected data (first 5 samples):
 [[-1.41421356]
 [ 0.        ]
 [ 1.41421356]]
